version: 2

updates:
  # Keep GitHub Actions versions up to date and supported
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "github-actions"
      - "dependencies"
